### ISSUE TITLE
Add support for ordering by given annotation id

### ISSUE THREAD

**Issue by llowinge** [jboss-soa-qa/phaser#22]
Every annotation should have unique id. Then the annotation can use after="<annotation-id>" and before="<annotation-id>".

**Comment by HEm3R** [comment]
@llowinge You mean the annotations describing phase? (main phase, second phase, ...)

**Comment by llowinge** [comment]
I mean annotations describing phases during container lifecycle (StaticConfigurationPhase, RuntimeSetupPhase, ..).

**Comment by HEm3R** [comment]
In Phaser there are no StaticConfigurationPhase, RuntimeSetumPhase, these must be part of different project using Phaser for own phase definition.

But I know, what do you mean. The ordering is already supported by order attribute which allow you to use orderable type by your choice.

But definitely, before/after is useful feature and you are free to contribute!

**Comment by llowinge** [comment]
You are right. I will look more deeper into that. It would be more easy to create phase flows without modification of already defined phases with fixed order.

**Comment by HEm3R** [comment]
@llowinge you can use double as type for order specification and user for example `order=1.5` to inject method between ordered methods in different job.
