### ISSUE TITLE
Add support for inject properties via annotation

### ISSUE THREAD

**Issue by osmman** [jboss-soa-qa/phaser#23]
It would be nice to add support for injection of system properties in script definitions. 

First possible solution and easiest is using existing annotation `@Inject`. Only what is needed is fill `InstanceRegistry` with Property objects.
```java
public class TestJob {

  @Inject("sys.property")
  private Property property;

  ...
}
```

Second possible solution is to create new annotation `@Property` which will load value from property register, convert it to target type and set filed.   
```java
public class TestJob {

  @Property("sys.property")
  private Integer property;

  @Property("sys.property2")
  private String property2;

  @Property("sys.projects")
  private Set<String> projects;
  
  ...
}
```

**Comment by basovnik** [comment]
Is is great idea. We could also develop an injectable `Context`  having method `getProperty`.

**Comment by HEm3R** [comment]
Yeah, great idea. Actually @Inject annotation is for injecting instances (and you can name your instance 'sys.property'. So as said @basovnik, we can create injectable Context with getProperty method - but it does not bring the intended effect, imho.

@Property looks more appropriate for that.

**Comment by basovnik** [comment]
I think about this issue again. Lets imagine the following code:
```java
	@Property("my-string")
	@Inject(id="my-string")
	private CharSequence myString;
```
Is the `@Property` annotation really necessary. If you want to use it for type `String` then it cannot be proxy. Is this expected behaviour?  What do you mean? Maybe the current state is sufficient. We can use interfaces for injecting.

**Comment by basovnik** [comment]
After talk with @osmman I understand advantages of this issue. `@Property` annotation will inject real objects, not proxy objects. It will allow us to inject any types we want (`int`, `boolean`, `String[]`, ...) and with custom `Context` implementation we can transfrom these objects as we want.

+1
